package masnoonislamicdua.sofit.com.masnoonduas;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.Toast;

public class DuaList extends AppCompatActivity {

    ListView listView;
    int position;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_dua_list);
        listView = (ListView) findViewById(R.id.list);

//        String[] values= new String[] {
//                "1: For Morning & Evening",
//                "2: When the sun rises recite",
//                "3: In the evening recite",
//                "4: After the expiry of Maghrib time recite this dua",
//                "5: Other supplications to be recited un the morning & evening",
//                "6: If one misses normal recitation of the day",
//                "7: Protection of calamities and ploys till the morning if recited in evening and vice versa",
//                "8: Praise Allah for the favours of morning and evening",
//                "9: Becomes the responsibility of Allah to satisfy him on the Day of Qiyamah if recited",
//                "10: A person who recites three times, 70,000 Angels pray for his mercy from morning till evening & Vice Versa if he die that day/night he dies as a martyr ",
//                "11: Surah Yaseen in morning",
//                "12: Supplications to be recited at night",
//                "13: Reward of performing his Salaat for the whole night",
//                "14: Surah Alif Laam Meem Sajda (21 para) and Surah Tabarakal Lazi",
//                "15: Allah will protect him from all evil and ploys",
//                "16: Sunnat's of Sleeping",
//                "17: Dua before sleep 1",
//                "18: Dua before sleep 2",
//                "19: Perform following and immune from everything besides death, before sleep KUI's",
//                "20: Tasbiat e Fatima and Ayat'ul Kursi before sleep",
//                "21: Astaghfar and gaining protection of Angels before sleep",
//                "22: When difficulty obtaining sleep",
//                "23: After having a nightmare",
//                "24: On having a good dream",
//                "25: On awakening of sleep Dua 1",
//                "26: On awakening of sleep Dua 2",
//                "27: On rising for thajjud recite",
//                "28: When entering the toilet",
//                "29: When coming out of toilet",
//                "30: At the begining of making wudu",
//                "31: During wudu",
//                "32: On completion of wudu Look towards the sky and recite",
//                "33: When going to Fajr Prayer",
//                "34: When entering the Masjid recite Durood and Salaam first and thereafter recite",
//                "35: Dua for Masjid",
//                "36: After Completion of Prayer in Masjid",
//                "37: When coming out of the Masjid 1",
//                "38: When coming out of Masjid 2",
//                "39: On hearing of Adhan",
//                "40: Upon hearing the Muazzin give Adhan",
//                "41: At the end of Adhan recite Durood then",
//                "42: The reply to the Iqamat",
//                "43: After te fard Salaat step 1 recite the following while rubbing the right hand oon the forehand",
//                "44: After the Fard Salaat step 2, 3 Times Astaghfaar then recite following",
//                "45: Individual Dua after fard prayer 1",
//                "46: Individual Dua after fard prayer 2",
//                "47: Individual Dua after fard prayer 3",
//                "49: Individual Dua after fard prayer 4",
//                "50: Individual Dua after fard prayer 5",
//                "51: Individual Dua after fard prayer 6",
//                "52: Ayatul Qursi after every Salaat",
//                "53: The Muwoozhiteen(i.e the four Quls) after every fard Salaat",
//                "54: After Fard Prayer Tasbeehat e Fatima then above Dua",
//                "55: After Witr Prayer",
//                "56: After Chasht (Forenoon) Prayer",
//                "57: After Fajr & Maghrib Prayer",
//                "58: Ten rewards written, ten sins removed, protection from every evil thing and no other sins besides shirk",
//                "59: When entering ones home",
//                "60: When buying or sellimg at the market",
//                "61: Before meals",
//                "62: On forgetting to recite Bismillah at beginning, recite",
//                "63: After meals Dua 1",
//                "64: After meals Dua 2",
//                "65: After meals Dua 3",
//                "66: After meals Dua 4",
//                "67: At the time of lifting the table cloth",
//                "68: When drinking milk",
//                "69: At meal times when visiting someone 1",
//                "70: At meal times when visiting someone 2",
//                "71: When leaving the residence of host",
//                "72: Whe drinking water and when finished drinking",
//                "73: Drinking Zam Zam water",
//                "74: When breaking fast 1",
//                "75: When breaking fast 2",
//                "76: After Iftaar",
//                "77: Making iftaar at someone's else place",
//                "78: When dressing",
//                "79: Wearing new clothes 1",
//                "80: Wearing new clothes 2",
//                "81: Seeing a muslim in new clothes",
//                "82: Looking in the mirror",
//                "83: Arrival of a bride and new animal",
//                "84: Congratulating the bridegroom",
//                "85: Intention of having relation of wife",
//                "86: When the sperm comes out, recite the following dua in the heart",
//                "87: When the child begins to talk",
//                "88: When sighting the new moon 1",
//                "89: Dua when sighting the new moon 2When biding farewell to someone going off on a journey",
//                "90: Dua for another person undertaken a journey",
//                "91: Dua by the traveler for the person wishing him farewell",
//                "92: Dua at the intention to undertake a journey",
//                "93: Dua when mounting or placing a foot on a stripe",
//                "94: When begining the journey recite",
//                "95: When climbing recite",
//                "96: Dua when travelling in a ship",
//                "97: When alighting off a vehicle recite",
//                "98: Seeing a Village/Town of the Destination",
//                "99: When entering any city or populated area",
//                "100: When night while on a journey",
//                "101: At time of sehri while on a journey",
//                "102: Suras when on a journey",
//                "103: Etiquettes on  returning from a journey",
//                "104: On the return journey when entering ones on city",
//                "105: When someone is in a difficulty",
//                "106: When one sees a muslim laughing",
//                "107: When fearing the enemy",
//                "108: When the enemy surrounds",
//                "109: Before rising from a gathering",
//                "110: When in any difficulty 1",
//                "111: When in any difficulty 2",
//                "112: When in any difficulty 3",
//                "113: When in any difficulty 4",
//                "114: When in any difficulty 5",
//                "115: Medicine for 99 aliments, the least of which is depression",
//                "116: Dua For the Night of Qadr (Power)",
//                "117: When you love someone make it known by saying:",
//                "118: Dua for the one who has aided you",
//                "119: Dua when the debtor pays his debt",
//                "120: When one sees the things one loves",
//                "121: When one's heart is filled with emotion",
//                "122: When something is lost",
//                "123: When one talks too fast",
//                "124: When eating new fruit of the season",
//                "125: At the time of anger or when hearing a donkey or a dog",
//                "126: Dua For Rain 1",
//                "127: Dua For Rain 2",
//                "128: When one sees heavy clouds",
//                "129: At the time of rain",
//                "130: When rain exceeds the limits",
//                "131: At the time of thunder",
//                "132: At the time of heavy winds",
//                "133: Talbiya of Hajj",
//                "134: Dua to be read at Arafat",
//                "135: While making Tawaaf",
//                "136: When making Qurbani",
//                "137: When meeting another Muslim 1",
//                "138: When meeting another Muslim 2",
//                "139: When meeting another Muslim 3",
//                "140: Returning Salaam",
//                "141: Dua when sneezing",
//                "142: When hearing someone sneeze",
//                "143: The person sneezing should then reply",
//                "144: Upon the thought of a bad omen",
//                "145: Dua to pay off debts",
//                "146: Another dua for payment of debt",
//                "147: Sayed-ul-Istighfaar (The leader of the duas of forgiveness)",
//                "148: Dua after salaat of need",
//                "149: Istikhara",
//                "150: When visiting the sick",
//                "151: Dua for good health of patient",
//                "152: When any calamity comes, even if pricked by a thorn recite",
//                "153: Infection on the body",
//                "154: Pain on the body",
//                "155: For the cure of any illness",
//                "156: To soothe ill children",
//                "157: Dua by an ill person",
//                "158: Dua forbid from fire of Jahannam . ",
//                "159: When death is eminent",
//                "160: When the soul is leaving the body",
//                "161: Kalima at Time of Death",
//                "162: Sura-e-Ya-Seen at time of Death",
//                "163: When the soul has left the body",
//                "164: When going to the deceased's house",
//                "165: When placing the dead person on the platform or whilst carrying them",
//                "166: When someone's child dies",
//                "167: When burying the dead",
//                "168: When entering the cemetry(Graveyard) Dua 1",
//                "169: When entering the cemetry(Graveyard) Dua 2",
//                "170: When consoling someone, greet with salaam and say",
//                "171: Prophet Mohammad's (SAW) action when bitten by a scorpion",
//                "172: At the time of fire",
//                "173: For any animal (cow/buffalo) that becomes sick",
//                "174: Read this and blow on the ailing eye",
//                "175: For eye pain",
//                "176: For kidney stone or urination problems",
//                "177: When fever or pain increases",
//                "178: Dua on a burn injury",
//                "179: When tired of life",
//                "180: Istikhara for Marriage"
//        };


        String[] COUNTRIES = new String[]{
                "For Morning & Evening",
                "When the sun rises recite",
                "In the evening recite",
                "After the expiry of Maghrib time, recite this dua",
                "Other supplications to be recited in the morning & evenings",
                "If one misses normal recitation of the day",
                "Protection from calamities and ploys till the morning if recited in evening and vice versa.",
                "Praise ALLAH for the favours of morning and evening",
                "Becomes the responsibility of Allah to satisfy him on the Day of Qiyamah if recited .",
                "A person who recites three times,70,000 Angels pray for his mercy from morning till evening & Vice Versa if he die that day/night he die as a martyr",
                "Surah Yaseen in  morning",
                "Supplications to be recited at night",
                "Reward of performing his Salaat for the whole night.",
                "Surah Alif Laam Meem Sajda (21 para) and Surah Tabarakal Lazi",
                "Allah will protect him from all evil and ploys",
                "Sunnat's of Sleeping",
                "Dua before sleep",
                "Dua before sleep",
                "Perform following and immune from everything besides death,before sleep KUl's",
                "Tasbiaht e Fatima and Ayat'ul Kursi before sleep",
                "Astaghfar and gaining protection of Angels before sleep",
                "When difficulty obtaining sleep",
                "After having a nightmare",
                "On having a good dream",
                "On awakening from sleep Dua",
                "On awakening from sleep Dua",
                "On rising for Tahajjud recite",
                "When entering the toilet",
                "When coming out of the toilet",
                "At the begining of making wudu",
                "During wudu",
                "On completion of wudu Look towards the sky and recite",
                "When going for Fajr Prayer",
                "When entering the Masjid recite Durood and Salaam first and thereafter recite",
                "Dua for Masjid",
                "After completion of prayer in Masjid",
                "When coming out of the Masjid",
                "When coming out of the Masjid",
                "On hearing the Athan",
                "Upon hearing the Muazzin give Athan",
                "At the end of the athaan recite Durood then",
                "The reply to the Iqamat",
                "After the fard Salaat step1 recite the following while rubbing the right hand on the forehead",
                "After the fard Salaat  step2 3times Astaghfar then recite following ",
                "Individual dua after Fard prayer",
                "Individual dua after Fard prayer",
                "Individual dua after Fard prayer",
                "Individual dua after Fard prayer",
                "Individual dua after Fard prayer",
                "Individual dua after Fard prayer",
                "Ayatul Qursi after every Salaat",
                "The Muwoozhiteen (i.e. the four Quls) after every fard Salaat.",
                "After Fard prayer Tasbeehat e Fatima then above Dua ",
                "After Witr Prayer", "After Chasht (Forenoon) Prayer",
                "After Fajr & Maghrib Prayer",
                "Ten rewards written,ten sins removed,protection form every evil thing and no other sin besides Shirk",
                "When entering ones home",
                "When leaving the house",
                "While Leaving home look towards the sky and recite",
                "When entering the Market",
                "When buying or selling at the Market",
                "Before meals",
                "On forgetting to recite Bismillah at the beginning, recite",
                "After Meals Dua",
                "After Meals Dua",
                "After Meals Dua",
                "After Meals Dua",
                "At the time of lifting the table cloth",
                "When drinking Milk",
                "At meal times when visiting someone",
                "At meal times when visiting someone",
                "When leaving the residence of the host",
                "When drinking water & when finished drinking",
                "Drinking Zam Zam water",
                "When breaking fast",
                "When breaking fast",
                "After Iftaar",
                "Making Iftaar at someone's place",
                "When dressing",
                "Wearing new clothes",
                "Wearing new clothes",
                "Seeing a muslim in new clothes",
                "looking in the mirror",
                "Arrival of a bride or a new animal",
                "Congratulating the bridegroom",
                "Intention of having relation with wife",
                "When the sperm comes out, recite the following dua in the heart",
                "When the child begins to talk",
                "When sighting the new moon",
                "Dua when sighting the new moon",
                "When biding farewell to someone going off on a journey",
                "Dua for another person undertaken a journey",
                "Dua at the time of his departure",
                "Dua by the traveller for the person wishing him farewell",
                "Dua at the intention to undertake a journey",
                "Dua when mounting or placing a foot on a stripe",
                "When beginning the journey recite",
                "When climbing recite:",
                "Dua when travelling in a ship",
                "When alighting off a vehicle recite",
                "Seeing the Village/Town of the Destination ",
                "When entering any city or a populated area",
                "When night while on a journey",
                "At the time of Sehri while on a journey",
                "Suras when on journey",
                "Etiquettes on returning from a journey",
                "On the return journey when entering one's own city ",
                "On the return from a journey",
                "When someone is in a difficulty",
                "When one sees a muslim laughing",
                "When fearing the enemy",
                "When the enemy surrounds",
                "Before rising from a gathering",
                "When in any difficulty",
                "When in any difficulty",
                "When in any difficulty",
                "When in any difficulty",
                "When in any difficulty",
                "Medicine for 99 ailments, the least of which is depression",
                "Dua For the Night of Qadr (Power)",
                "When you love someone make it known by saying:",
                "Dua for the one who has aided you",
                "Dua when the debtor pays his debt",
                "When one sees the things one loves",
                "When one's heart is filled with emotion",
                "When something is lost",
                "When one talks too fast",
                "When eating new fruit of the season",
                "At the time of anger or when hearing a donkey or a dog",
                "Dua For Rain", "Dua For Rain",
                "When one sees heavy clouds",
                "At the time of rain",
                "When rain exceeds the limits",
                "At the time of thunder",
                "At the time of heavy winds",
                "Talbiya of Hajj",
                "Dua to be read at Arafat",
                "While making Tawaaf",
                "When making Qurbani",
                "When meeting another Muslim",
                "When meeting another Muslim",
                "When meeting another Muslim",
                "Returning Salaam",
                "Dua when sneezing",
                "When hearing someone sneeze",
                "The person sneezing should then reply",
                "Upon the thought of a bad omen",
                "Dua to pay off debts",
                "Another dua for payment of debt",
                "Sayed-ul-Istighfaar (The leader of the duas of forgiveness)",
                "Dua after salaat of need",
                "Istikhara",
                "When visiting the sick",
                "Dua for good health of patient",
                "When any calamity comes, even if pricked by a thorn recite",
                "Infection on the body",
                "Pain on the body",
                "For the cure of any illness",
                "To soothe ill children",
                "Dua by an ill person",
                "Dua forbid from fire of Jahannam . ",
                "When death is eminent",
                "When the soul is leaving the body",
                "Kalima at Time of Death",
                "Sura-e-Ya-Seen at time of Death",
                "When the soul has left the body",
                "When going to the deceased's house",
                "When placing the dead person on the platform or whilst carrying them",
                "When someone's child dies",
                "When burying the dead",
                "When entering the cemetry(Graveyard) Dua",
                "When entering the cemetry(Graveyard) Dua",
                "When consoling someone, greet with salaam and say",
                "Prophet Mohammad's (SAW) action when bitten by a scorpion",
                "At the time of fire",
                "For any animal (cow/buffalo) that becomes sick",
                "Read this and blow on the ailing eye",
                "For eye pain",
                "For kidney stone or urination problems",
                "When fever or pain increases",
                "Dua on a burn injury",
                "When tired of life",
                "Istikhara for Marriage"};

        ArrayAdapter<String> adapter= new ArrayAdapter<String>(this,android.R.layout.simple_list_item_1,COUNTRIES);

        listView.setAdapter(adapter);

        listView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> adapterView, View view, int posit, long l) {
                position=posit;
               // Toast.makeText(DuaList.this, position, Toast.LENGTH_SHORT).show();
                Intent i = new Intent(DuaList.this, Details.class);
                i.putExtra("index", position);
                DuaList.this.startActivity(i);
                Log.e("Position", String.valueOf(position));
            }
        });
    }
}
